Repository OnBoarding-Park-is-best/week2-partners-dashboard, pull requests merged in 2022-02, with the labels that each got.

#2 :sparkles: feat: json-server 환경 구성
  json-server.json
  json-server/db.json
  json-server/index.js
  package.json
  src/api/fetchApi.ts
  src/api/index.ts
  src/constants/api.ts
  src/constants/index.ts
  src/types/api.ts
  src/types/index.ts
  yarn.lock
Labels: enhancement

#8 feat: Button base 컴포넌트 구현
  craco.config.js
  src/assets/images/refresh.png
  src/components/base/Button/Button.stories.tsx
  src/components/base/Button/Button.tsx
  src/components/base/ResetButton/ResetButton.stories.tsx
  src/components/base/ResetButton/ResetButton.tsx
  tsconfig.path.json
Labels: 리뷰요청, Feature

#9 :sparkles: feat: NavBar 컴포넌트 구현
  .storybook/preview-head.html
  .storybook/preview.js
  craco.config.js
  src/assets/images/colorlogo.png
  src/assets/images/logo.png
  src/components/domain/NavBar/NavBar.stories.tsx
  src/components/domain/NavBar/NavBar.tsx
  src/components/domain/index.ts
  src/constants/index.ts
  src/constants/style.ts
  src/styles/globals.tsx
  tsconfig.path.json
Labels: 리뷰요청, Feature

#13 :sparkles: feat: DefaultContainer 컴포넌트 작성
  src/components/domain/DefaultContainer/DefaultContainer.stories.tsx
  src/components/domain/DefaultContainer/DefaultContainer.tsx
Labels: 리뷰요청

#14 feat: ItemCard 컴포넌트 구현
  json-server/index.js
  src/components/base/index.ts
  src/components/domain/ItemCard/ItemCard.stories.tsx
  src/components/domain/ItemCard/ItemCard.tsx
  src/components/domain/index.ts
  src/constants/style.ts
Labels: 리뷰요청, Feature
